### ISSUE TITLE
Web Socket Error when trying to run the client on  vue-fullstack-basic   

### ISSUE THREAD

**Issue by lenzino** [graphql-boilerplates/vue-fullstack-graphql#235]
After setting up the boilerplate, When I try to open  'http://localhost:8080/' on the browser, the page keeps refreshing and I get the following error: "WebSocket connection to 'wss://localhost:4000/' failed: Websocket is closed before the connection is established "

Additionally, I get the following error too. "Error sending the query 'feed' ReferenceError: getMainDefinition is not defined"

What am I missing? 

**Screenshot:**
![image](https://user-images.githubusercontent.com/136755/38782620-f2bbc20a-4113-11e8-895c-c0ef23c3f589.png)

**Comment by Neekhaulas** [comment]
I have the same error

**Comment by juicycleff** [comment]
Ok that's a `wss` bug issue. It cane up after the recent prisma update. Work around is ro change the `wss` to `ws` . I will make a pr to resolve it

**Comment by juicycleff** [comment]
This issue has been resolved. Closing this issue.

**Comment by halton** [comment]
I'm running the basic with my local endpoint with HEAD at 298ba0621ab0d23dce3f85fc5a4429b99dbfba4f, this error still valid to me.
